[project]
name = "ansible-utils"
version = "0.0.0"
description = ""
requires-python = ">=3.8"
dependencies = []

[dependency-groups]
dev = [
  "pokerops-ansible-utils@git+https://github.com/pokerops/ansible-utils@master",
]

[tool.uv.dependency-groups]
dev = { requires-python = ">=3.12" }
